sudo: false

language: go

go:
- 1.10.x
- master

git:
  depth: 1

matrix:
  allow_failures:
  - go: master
  fast_finish: true

install:
- go get github.com/kardianos/govendor
- go get -u github.com/client9/misspell/cmd/misspell
- go get -u honnef.co/go/tools/cmd/megacheck

before_script:
- EXCLUDE_VENDOR=$(find . -not -path "./vendor/*" -name "*.go")
- EXCLUDE_VET=$(find . -not -path "./vendor/*" -not -path "./model-generator/*" -name "*.go")
- govendor sync
- go vet $EXCLUDE_VET
- (cd model-generator && go vet $(find . -not -path "./test-schemas/*" -name "*.go"))
- misspell -error -locale US *.go
- megacheck $EXCLUDE_VENDOR
- (for file in $EXCLUDE_VENDOR; do diff -u <(echo -n) <(gofmt -d -s $file) || exit 1; done)
- $(exit $(govendor list -no-status +outside | wc -l))

script: make test

notifications:
  slack:
    secure: m8ec8U2CqPqLQPvFuvIjkI2n82mFVzJ2c/xkfV5gDrc5ujiZNKaw3GHbPbjc9Mr2b8z5vCRGKTKRNO4zGuognoOckvyAAHfxS4lpPcpwOWrSEZN4TGKW4tpCr453VaxLT34Pcjfi5pPxamHcYOzgl7SWrAv1aGgDZ5QWeVlQU7pB14nxJnWFc9FW3B6FKcXxiDOEbjCDFHSHl7xcs0E8qb7rSCYD2nTncXPTwfA2dqoij72VjwIVrddxwMgA+jJvnb0ScP3Z3G0oz6TZCZLVzxw6V6EMQf54SLVsfWe74xAUcbaUeWk5sijXt4yLeQheZcJpgOXqRQ0LIZWhNcAqYNqIlFesTtlVbN45L2xW10a308PV8ZrX/Svm09CYIliZuwC10HO49x7lGswL1eBIM2ZxYEmTXg6/EHOBm0MLirKUwwkj9O8R4tsE0te1IcTmZLZ4Doh++xKQhdRMlrcALEZ4zR5J8zAGW2VxFsKYZ6pNPqiA9aBB/6WE1fl7vaUPsIIbV82186apLWAdX78BIMcTJEi7erK8Vqqx6yNnxl9gZlYNU4MKd4Kd7SHqHsoeZgUIPy/ctLIDb1rs639tMcIy6RBc01KN4l+ZwdwAsunD8rHxVPF8mZVJ/O46Tf8vrOziA6EdpT676TjB6fAj7Q+8JKx+NAcMndRKLcJlsew=
